### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ontech7** [ontech7/event_interpreter_validator#1]
- [ ] Add maybe some annotations with @
- [ ] Implement 'while'
- [ ] Implement arrays (with 'options-endoptions' statements)
- [ ] Implement 'not' type
- [ ] Implement logs in a file
- [x] Fix set, add, sub, mul, div 2nd argument (check if INTEGER).
- [x] Implement 'else' in 'if-endif' statements
- [x] Implement constants
- [x] Implement "return" keyword to end functions.
- [x] Make flags for logger, in order to filter logger levels.
